// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CollapseController from "./collapse_controller"
application.register("collapse", CollapseController)

import CommentController from "./comment_controller"
application.register("comment", CommentController)

import EventFilterController from "./event_filter_controller"
application.register("event-filter", EventFilterController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import PhotoUploadController from "./photo_upload_controller"
application.register("photo-upload", PhotoUploadController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import UserSearchController from "./user_search_controller"
application.register("user-search", UserSearchController)
