default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  variables:
    statement_timeout: 5000

development:
  <<: *default
  database: private_events
  username: csi_local

test:
  <<: *default
  database: private_events_test
  username: csi_local
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>  